#!/bin/bash

FONT="Misc Ohsnapu:size=8"
ICON="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
GEOM="1366x15+0+0" # 1366x768 screen
FORE="#ebdbb2"
#FORE="#000000"
#FORE="#ffffff"
BACK="#bf000000"
#BACK="#50000000"
#BACK="#00000000" # fully transparent
TLINE=1 #thickness
CLINE="#ebdbb2"

./lemon-content.lua | lemonbar -b -p -o 1 -f "$FONT" -f "$ICON" -g "$GEOM" -F $FORE -B $BACK -u $TLINE -U $CLINE -a 100 | bash
